# permissions for end users to view deploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-viewer-role
rules:
- apiGroups:
  - tfk.github.com
  resources:
  - deploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tfk.github.com
  resources:
  - deploys/status
  verbs:
  - get
