apiVersion: tfk.github.com/v1beta1
kind: Deploy
metadata:
  name: deploy-sample
  namespace: tfk
spec:
  # TODO(user): Add fields here
  serviceAccount: "test"
  terraform:
    image: "hashicorp/terraform"
    commands: ["apply"]
    version: "1.3.0"
  source:
    repo: "https://github.com/tony-mw/tfk.git"
    refresh-interval: 120
    branch: "main"
    entryPoint: "terraformData"
  state:
    url: "test"
